version: '3.9'
services:
  app:
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - ${RUST_PORT}:${RUST_PORT}
    volumes:
      - ./server:/app
    depends_on:
      - db
    tty: true

  db:
    image: mysql:8
    command: --log-bin-trust-function-creators=1
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    platform: linux/arm64
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db:/var/lib/mysql

networks:
  sample-aws:
    driver: bridge

volumes:
  db: