FROM rust:1.70.0-slim-bullseye

WORKDIR /app

RUN apt update -y && apt upgrade -y
RUN apt install -y pkg-config libssl-dev
RUN apt install -y default-mysql-client default-libmysqlclient-dev

COPY migrations/ migrations/
COPY Cargo.toml Cargo.toml
COPY Cargo.lock Cargo.lock

RUN cargo install sqlx-cli
